name: Ruby on Rails CI

on:
  workflow_dispatch:
    inputs:
      run_system_tests:
        description: "Run system tests"
        required: false
        default: "false"
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: my_database
          POSTGRES_USER: my_user
          POSTGRES_PASSWORD: my_password
        options: >-
          --health-cmd "pg_isready -U my_user"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1" # Adjust the Ruby version as needed

      - name: Install dependencies
        run: bundle install

      - name: Install Chromium and xvfb
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser xvfb

      - name: Run unit tests
        run: bundle exec rspec spec/models spec/controllers # Run only unit tests

      - name: Run system tests
        if: ${{ github.event.inputs.run_system_tests == 'true' }} # Run system tests based on input
        env:
          DISPLAY: :99
          CHROME_BIN: /usr/bin/chromium-browser
        run: |
          Xvfb :99 -screen 0 1280x1024x24 &
          bundle exec rake db:create db:schema:load
      - name: Run tests
        run: bundle exec rake test:run
