name: Ruby on Rails CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true

      - name: Install Gems
        run: bundle install

  database:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Database Schema
        run: bin/rails db:schema:load

  test:
    runs-on: ubuntu-latest
    needs: [setup, database]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests
        run: bin/rails test

  lint:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Gems
        run: bundle install

      - name: Lint Ruby Files
        run: bundle exec rubocop --parallel
